pipeline {
    agent any

    stages {

        stage('build') {
            steps {
                sh 'echo build'
            }
        }

        stage('test') {
            steps {
                sh 'echo test'
            }
        }

        stage('push') {
            steps {
                sh 'echo push'
            }
        }

        stage('deploy') {
            steps {
                sh 'echo deploy'
            }
        }
    }
}